version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--accessLog.filePath=/var/log/access.log"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.php.address=:9000"      
      - "--entrypoints.web.address=:80"
    ports:
      - "90:9000"
      - "80:80"      
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  php72:
    build:
        context: ./docker/PHP-7.2
        dockerfile: Dockerfile          
    volumes:
        - ./src:/var/www/html
        - ./config/PHP-7.2:/volume/config
        - ./data:/volume/data
        - ./log/php72:/volume/log
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php72.rule=Host(`php72.localhost`)"
      - "traefik.http.routers.php72.entrypoints=php"    